package dao

var (
	Sign            *sign
	BookCounter     *bookCounter
	Seo             *seo
	Document        *document
	Comments        *comments
	ReadingTime     *readingTime
	Wechat          *wechat
	FriendLink      *friendLink
	Awesome         *awesome
	Relationship    *relationship
	Banner          *banner
	BookCategory    *bookCategory
	Star            *star
	DocumentStore   *documentStore
	GithubUser      *githubUser
	Member          *member
	Label           *label
	Bookmark        *bookmark
	AwesomeCate     *awesomeCate
	AdsCont         *adsCont
	Logs            *logs
	Github          *github
	Score           *score
	Book            *book
	DocumentHistory *documentHistory
	ReadRecord      *readRecord
	ReadCount       *readCount
	Category        *category
	MemberToken     *memberToken
	Attachment      *attachment
	Option          *option
	Fans            *fans
)
