package dao

var (
	ReadingTime     *readingTime
	DocumentStore   *documentStore
	Comments        *comments
	BookCounter     *bookCounter
	Seo             *seo
	Wechat          *wechat
	BookCategory    *bookCategory
	Fans            *fans
	Attachment      *attachment
	ReadRecord      *readRecord
	FriendLink      *friendLink
	MemberToken     *memberToken
	Document        *document
	Score           *score
	DocumentHistory *documentHistory
	Sign            *sign
	Bookmark        *bookmark
	Label           *label
	GithubUser      *githubUser
	Member          *member
	Relationship    *relationship
	Awesome         *awesome
	ReadCount       *readCount
	Banner          *banner
	Logs            *logs
	Category        *category
	User            *user
	AwesomeCate     *awesomeCate
	Option          *option
	Tool            *tool
	Star            *star
	AdsCont         *adsCont
	Book            *book
)
