package dao

var (
	ReadRecord      *readRecord
	FriendLink      *friendLink
	Score           *score
	Option          *option
	Logs            *logs
	Github          *github
	ReadingTime     *readingTime
	Comments        *comments
	GithubUser      *githubUser
	Category        *category
	DocumentStore   *documentStore
	ReadCount       *readCount
	Sign            *sign
	Wechat          *wechat
	Banner          *banner
	Star            *star
	Attachment      *attachment
	BookCounter     *bookCounter
	BookCategory    *bookCategory
	Bookmark        *bookmark
	AdsCont         *adsCont
	Relationship    *relationship
	Book            *book
	DocumentHistory *documentHistory
	Label           *label
	Awesome         *awesome
	Seo             *seo
	User            *user
	MemberToken     *memberToken
	AwesomeCate     *awesomeCate
	Fans            *fans
	Document        *document
	Member          *member
)
